### PR TITLE
Added Paytm Bug Bounty Program

### PR DESCRIPTION
**Pull request by realabbas**
# Paytm Bug Bounty Program

image

[Link](https://bugbounty.paytm.com/)

### CODE REVIEW

**Comment by djadmin** [comment]
Thanks 👍

**Review by lopezregalodelo-a11y — CHANGES_REQUESTED** [review]
Updated apps

**Review by lopezregalodelo-a11y — COMMENTED** [review]
Updated

**Review by lopezregalodelo-a11y — APPROVED** [review]
Update

**Pull request merged**
