### PR TITLE
Adding ChainTip bounties to the list of platforms.

### LINKED ISSUE #20: chaintip is a bitcoin cash bounties bot that integrates directly into github
info is here
https://github.com/chaintip/bounties

### PR DESCRIPTION
**Pull request by block-spider**
@chaintip fixes #20

Linked to the issue tipping section on the GitHub usage page of the ChainTip site. This position on the page clearly shows how to create and claim bounties.

@djadmin, please modify this inclusion as you desire. This @block-spider account is a helper account for ChainTip.

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#20](http://github.chaintip.org/djadmin/awesome-bug-bounty/issues/20) first, @block-spider will claim the `0.0005 BCH`| `~   0.52 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/23) and all future tips to the issue.

**Comment by djadmin** [comment]
Unfortunately, I have to close this PR since the repository is specific to security.

**Comment by chaintip** [comment]
I see, no problem. If/when there are enough security related bounties on ChainTip Bounties, I'll try again linking to the security section only.

**Comment by block-spider** [comment]
@chaintip

**Comment by block-spider** [comment]
@djadmin @chaintip

**Comment by chaintip** [comment]
[chaintip](http://www.chaintip.org) has [returned](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld498wuqrj03tlfk55hsjt5u9xzw7qzu76u8hh) the unclaimed tip of `0.00221779 BCH`| `~   2.19 USD` to @block-spider.

**Pull request closed without merging**
