### PR TITLE
Updated @riyazwalikar website address

### PR DESCRIPTION
**Pull request by 0xbadshah**

### CODE REVIEW

**Comment by djadmin** [comment]
Thanks 👍

**Review by lopezregalodelo-a11y — COMMENTED** [review]
.....

**Review by lopezregalodelo-a11y — APPROVED** [review]
.....

**Review by lopezregalodelo-a11y — CHANGES_REQUESTED** [review]
......

**Review by lopezregalodelo-a11y — CHANGES_REQUESTED** [review]
.......

**Pull request merged**
